# Configuration cmake lists for the project
set(ENABLE_MODULE_POINTERS ON CACHE BOOL "" FORCE)
set(ENABLE_MODULE_ARRAYS OFF CACHE BOOL "" FORCE)
set(ENABLE_MODULE_STRINGS OFF CACHE BOOL "" FORCE) #Strings need Arrays to be enebaled
set(ENABLE_MODULE_STRINGS_ASSIGNMENTS ON CACHE BOOL "" FORCE)
set(ENABLE_MODULE_FUNCTIONS ON CACHE BOOL "" FORCE)