name: Build and Analyze Memory Leak

on: 
  push: 
    branches: 
      - '*' 
  pull_request: 
    branches: 
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Valgrind and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install valgrind  
      - name: Run build command
        run: |
          cmake -S . -B build
          cmake --build build --target cpp_app        
      - name: Analyze Memory Leak
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.c" -o -name "*.h" \) -exec valgrind --leak-check=full --error-exitcode=1 {} \;

      - name: Run code beautifier
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.c" -o -name "*.h" \) -exec uncrustify -c uncrustify.cfg --no-backup {} \;
